dist: xenial
language: php
sudo: required

php: "7.2"

addons:
    apt:
        sources:
            -   sourceline: ppa:ondrej/php
        update: true

before_install:
    - sudo apt install php7.3-snmp
